export default {
  th: {
    menu: {
      carcare: 'ดูแลรถยนต์',
      booking: 'จองคิวออนไลน์',
      home: 'หน้าหลัก',
      member: 'สมาชิกพิเศษ',
      queue: 'สถานะคิว',
      login: 'เข้าสู่ระบบ',
      register: 'สมัครสมาชิก',
      nopage: 'ไม่มีหน้านี้',
      header: 'ส่วนหัว',
      services: 'บริการ',
    },
    banner: {
      title: 'ส่งฟรี เมื่อยอดการสั่งซื้อเกิน ฿3000',
    },
    usernav: {
      languageEN: 'English',
      languageTH: 'Thailand',
      darkmode: 'โหมดกลางคืน',
      lightmode: 'โหมดกลางวัน',
      login: 'เข้าสู่ระบบ',
      logout: 'ออกจากระบบ',
      adminmode: 'โหมดแอดมิน',
      usermode: 'โหมดผู้ใช้งาน',
    },
  },
  en: {
    menu: {
      carcare: 'Car Care',
      booking: 'Booking',
      home: 'Home',
      member: 'Member Pass',
      queue: 'Queue status',
      login: 'Login',
      register: 'Register',
      nopage: 'No Page',
      header: 'Header',
      services: 'Services',
    },
    banner: {
      title: 'Get free delivery on orders over $100',
    },
    usernav: {
      languageTH: 'ภาษาไทย',
      languageEN: 'ภาษาอังกฤษ',
      darkmode: 'Dark Mode',
      lightmode: 'Light Mode',
      login: 'Login',
      logout: 'Logout',
      adminmode: 'Admin Mode',
      usermode: 'User Mode',
    },
  },
};
